# Generated by Django 4.1 on 2023-10-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_persons_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
    ]
